// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eptppcecajzkwuvsgton.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwdHBwY2VjYWp6a3d1dnNndG9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2OTExNTgsImV4cCI6MjA3OTI2NzE1OH0.ZKA8wUjh7A1u1DI2KLGHhv_N-kk7wbLP028g2vc7jnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});